### ISSUE TITLE
How to load the wasm file from the npm package?

### ISSUE THREAD

**Issue by jens-duttke** [Daninet/rubberband-wasm#2]
Here:
https://github.com/Daninet/rubberband-wasm/blob/5d92515e2e01cc4ebf889bf6742f552d931c155d/demo/worker.js#L7
You are simply load the wasm file from the folder itself.
But how can I do that in my code, if I'm using your npm-package?

Is there an example which uses your npm package and does it without WebWorker?

**Comment by Daninet** [comment]
I advice against using it without webworkers because it might block the main thread and make the UI freeze.
Importing depends on your bundler configuration. But you can try something like this:
`fetch("rubberband-wasm/dist/rubberband.wasm")`
`fetch("rubberband-wasm/dist/rubberband.wasm?url")`
